// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userd.proto

/*
Package userdpb is a generated protocol buffer package.

It is generated from these files:
	userd.proto
	userservice.proto

It has these top-level messages:
	User
	NewUser
	CheckUser
	FollowerDetails
	NewUserRequest
	NewUserResponse
	GetUserRequest
	GetUserResponse
	ValidateUserRequest
	FollowUserRequest
	FollowUserResponse
	FollowerDetailsRequest
	FollowerDetailsResponse
*/
package userdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UID         string   `protobuf:"bytes,1,opt,name=UID,json=uID" json:"UID,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Email       string   `protobuf:"bytes,3,opt,name=Email,json=email" json:"Email,omitempty"`
	Password    string   `protobuf:"bytes,4,opt,name=Password,json=password" json:"Password,omitempty"`
	FollowerUID []string `protobuf:"bytes,5,rep,name=FollowerUID,json=followerUID" json:"FollowerUID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFollowerUID() []string {
	if m != nil {
		return m.FollowerUID
	}
	return nil
}

type NewUser struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *NewUser) Reset()                    { *m = NewUser{} }
func (m *NewUser) String() string            { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()               {}
func (*NewUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckUser struct {
	Email    string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *CheckUser) Reset()                    { *m = CheckUser{} }
func (m *CheckUser) String() string            { return proto.CompactTextString(m) }
func (*CheckUser) ProtoMessage()               {}
func (*CheckUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CheckUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CheckUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type FollowerDetails struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	UID      string `protobuf:"bytes,2,opt,name=UID,json=uID" json:"UID,omitempty"`
	Followed bool   `protobuf:"varint,3,opt,name=Followed,json=followed" json:"Followed,omitempty"`
}

func (m *FollowerDetails) Reset()                    { *m = FollowerDetails{} }
func (m *FollowerDetails) String() string            { return proto.CompactTextString(m) }
func (*FollowerDetails) ProtoMessage()               {}
func (*FollowerDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FollowerDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FollowerDetails) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *FollowerDetails) GetFollowed() bool {
	if m != nil {
		return m.Followed
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "userd.User")
	proto.RegisterType((*NewUser)(nil), "userd.NewUser")
	proto.RegisterType((*CheckUser)(nil), "userd.CheckUser")
	proto.RegisterType((*FollowerDetails)(nil), "userd.FollowerDetails")
}

func init() { proto.RegisterFile("userd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x95, 0x63, 0x9b, 0xda, 0x97, 0x01, 0x64, 0x31, 0x58, 0x9d, 0xa2, 0x4c, 0x9d, 0x58, 0x98,
	0x59, 0x20, 0x20, 0x75, 0x29, 0x28, 0xa8, 0x0b, 0x9b, 0x4b, 0x0e, 0x51, 0xe1, 0xe0, 0xc8, 0x6e,
	0x95, 0x95, 0x9f, 0x8e, 0x7a, 0xb8, 0x54, 0xa0, 0x76, 0x7c, 0xcf, 0x7a, 0x1f, 0x7e, 0x07, 0xe5,
	0x36, 0x61, 0xec, 0xae, 0x86, 0x18, 0x36, 0xc1, 0x48, 0x02, 0xf5, 0x17, 0x03, 0xb1, 0x4c, 0x18,
	0xcd, 0x05, 0xf0, 0xe5, 0xbc, 0xb1, 0xac, 0x62, 0x33, 0xdd, 0xf2, 0xed, 0xbc, 0x31, 0x06, 0xc4,
	0xc2, 0xf5, 0x68, 0x0b, 0xa2, 0xc4, 0xa7, 0xeb, 0xd1, 0x5c, 0x82, 0xbc, 0xef, 0xdd, 0xda, 0x5b,
	0x4e, 0xa4, 0xc4, 0x1d, 0x30, 0x53, 0x50, 0x4f, 0x2e, 0xa5, 0x31, 0xc4, 0xce, 0x0a, 0x7a, 0x50,
	0x43, 0xc6, 0xa6, 0x82, 0xf2, 0x21, 0x78, 0x1f, 0x46, 0x8c, 0x3b, 0x7f, 0x59, 0xf1, 0x99, 0x6e,
	0xcb, 0xb7, 0x03, 0x55, 0x3f, 0xc2, 0x64, 0x81, 0x23, 0x95, 0xd8, 0x47, 0xb2, 0x63, 0x91, 0xc5,
	0xa9, 0x48, 0xfe, 0x37, 0xb2, 0xbe, 0x01, 0x7d, 0xf7, 0x8e, 0xaf, 0x1f, 0x64, 0xf9, 0x2b, 0x67,
	0xa7, 0xe4, 0xc5, 0x3f, 0xf9, 0x33, 0x9c, 0xef, 0x1b, 0x37, 0xb8, 0x71, 0x6b, 0x9f, 0x8e, 0xf6,
	0xca, 0x83, 0x15, 0x87, 0xc1, 0xa6, 0xa0, 0xb2, 0xf0, 0xa7, 0x93, 0x6a, 0x55, 0xfe, 0x67, 0x77,
	0xab, 0x5f, 0x26, 0x34, 0xf8, 0xb0, 0x5a, 0x9d, 0xd1, 0x01, 0xae, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0xfe, 0xa2, 0xe6, 0x8f, 0x01, 0x00, 0x00,
}
