// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userd.proto

/*
Package userdpb is a generated protocol buffer package.

It is generated from these files:
	userd.proto
	userservice.proto

It has these top-level messages:
	User
	NewUser
	NewUserRequest
	NewUserResponse
	GetUserRequest
	GetUserResponse
*/
package userdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UID      string `protobuf:"bytes,1,opt,name=UID,json=uID" json:"UID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type NewUser struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *NewUser) Reset()                    { *m = NewUser{} }
func (m *NewUser) String() string            { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()               {}
func (*NewUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "userd.User")
	proto.RegisterType((*NewUser)(nil), "userd.NewUser")
}

func init() { proto.RegisterFile("userd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d,
	0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe2, 0xb8, 0x58, 0x42,
	0x8b, 0x53, 0x8b, 0x84, 0x04, 0xb8, 0x98, 0x43, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x98, 0x4b, 0x3d, 0x5d, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0,
	0x42, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0xae, 0xb9, 0x89, 0x99, 0x39, 0x12,
	0xcc, 0x60, 0x41, 0xd6, 0x54, 0x10, 0x47, 0x48, 0x8a, 0x8b, 0x23, 0x20, 0xb1, 0xb8, 0xb8, 0x3c,
	0xbf, 0x28, 0x45, 0x82, 0x05, 0x2c, 0xc1, 0x51, 0x00, 0xe5, 0x2b, 0xf9, 0x73, 0xb1, 0xfb, 0xa5,
	0x96, 0x83, 0xad, 0x80, 0x19, 0xc8, 0x88, 0xcd, 0x40, 0x26, 0x5c, 0x06, 0x32, 0xa3, 0x1a, 0xe8,
	0xc4, 0x19, 0xc5, 0x0e, 0x76, 0x79, 0x41, 0x52, 0x12, 0x1b, 0xd8, 0x27, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x87, 0x48, 0xf5, 0xd8, 0x00, 0x00, 0x00,
}
