sudo: false

language: go
go:
- tip # The latest version of Go.
install: true
notifications:
  emails: false
before_script:
  - go install github.com/golang/net
  - go install github.com/golang.org/sys/unix
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)