sudo: false

language: go
go:
- tip # The latest version of Go.
env:
- GO111MODULE=on
install: true
notifications:
  emails: false
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)