// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userd.proto

package userdpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UID                  string   `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	FollowingUID         []string `protobuf:"bytes,5,rep,name=FollowingUID,proto3" json:"FollowingUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c6daf5bb6a59b57, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFollowingUID() []string {
	if m != nil {
		return m.FollowingUID
	}
	return nil
}

type NewUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c6daf5bb6a59b57, []int{1}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUser) Reset()         { *m = CheckUser{} }
func (m *CheckUser) String() string { return proto.CompactTextString(m) }
func (*CheckUser) ProtoMessage()    {}
func (*CheckUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c6daf5bb6a59b57, []int{2}
}

func (m *CheckUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUser.Unmarshal(m, b)
}
func (m *CheckUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUser.Marshal(b, m, deterministic)
}
func (m *CheckUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUser.Merge(m, src)
}
func (m *CheckUser) XXX_Size() int {
	return xxx_messageInfo_CheckUser.Size(m)
}
func (m *CheckUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUser.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUser proto.InternalMessageInfo

func (m *CheckUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CheckUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type FollowerDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	UID                  string   `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Followed             bool     `protobuf:"varint,3,opt,name=Followed,proto3" json:"Followed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerDetails) Reset()         { *m = FollowerDetails{} }
func (m *FollowerDetails) String() string { return proto.CompactTextString(m) }
func (*FollowerDetails) ProtoMessage()    {}
func (*FollowerDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c6daf5bb6a59b57, []int{3}
}

func (m *FollowerDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerDetails.Unmarshal(m, b)
}
func (m *FollowerDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerDetails.Marshal(b, m, deterministic)
}
func (m *FollowerDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerDetails.Merge(m, src)
}
func (m *FollowerDetails) XXX_Size() int {
	return xxx_messageInfo_FollowerDetails.Size(m)
}
func (m *FollowerDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerDetails.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerDetails proto.InternalMessageInfo

func (m *FollowerDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FollowerDetails) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *FollowerDetails) GetFollowed() bool {
	if m != nil {
		return m.Followed
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "userd.User")
	proto.RegisterType((*NewUser)(nil), "userd.NewUser")
	proto.RegisterType((*CheckUser)(nil), "userd.CheckUser")
	proto.RegisterType((*FollowerDetails)(nil), "userd.FollowerDetails")
}

func init() { proto.RegisterFile("userd.proto", fileDescriptor_4c6daf5bb6a59b57) }

var fileDescriptor_4c6daf5bb6a59b57 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d,
	0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x9a, 0x18, 0xb9, 0x58,
	0x42, 0x8b, 0x53, 0x8b, 0x84, 0x04, 0xb8, 0x98, 0x43, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x10,
	0x98, 0x2d, 0x24, 0xc2, 0xc5, 0xea, 0x9a, 0x9b, 0x98, 0x99, 0x23, 0xc1, 0x0c, 0x16, 0x84, 0x70,
	0x84, 0xa4, 0xb8, 0x38, 0x02, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x58, 0xc0, 0x12,
	0x70, 0xbe, 0x90, 0x12, 0x17, 0x8f, 0x5b, 0x7e, 0x4e, 0x4e, 0x7e, 0x79, 0x66, 0x5e, 0x3a, 0xc8,
	0x02, 0x56, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x14, 0x31, 0x25, 0x7f, 0x2e, 0x76, 0xbf, 0xd4, 0x72,
	0xb0, 0x33, 0x60, 0x96, 0x32, 0x62, 0xb3, 0x94, 0x09, 0x97, 0xa5, 0xcc, 0xa8, 0x96, 0x2a, 0xd9,
	0x72, 0x71, 0x3a, 0x67, 0xa4, 0x26, 0x67, 0x83, 0x8d, 0x84, 0x6b, 0x67, 0xc4, 0xa5, 0x9d, 0x09,
	0x4d, 0x7b, 0x30, 0x17, 0x3f, 0xc4, 0x7d, 0xa9, 0x45, 0x2e, 0xa9, 0x25, 0x89, 0x99, 0x39, 0xc5,
	0x58, 0xdd, 0x05, 0x0d, 0x32, 0x26, 0x44, 0x90, 0x49, 0x71, 0x71, 0x40, 0x35, 0x42, 0xdc, 0xc4,
	0x11, 0x04, 0xe7, 0x3b, 0x71, 0x46, 0xb1, 0x83, 0x83, 0xbc, 0x20, 0x29, 0x89, 0x0d, 0x1c, 0x05,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x9f, 0x3b, 0x2d, 0x91, 0x01, 0x00, 0x00,
}
