// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftservice.proto

package raftdpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RaftGetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftGetRequest) Reset()         { *m = RaftGetRequest{} }
func (m *RaftGetRequest) String() string { return proto.CompactTextString(m) }
func (*RaftGetRequest) ProtoMessage()    {}
func (*RaftGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{0}
}

func (m *RaftGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftGetRequest.Unmarshal(m, b)
}
func (m *RaftGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftGetRequest.Marshal(b, m, deterministic)
}
func (m *RaftGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGetRequest.Merge(m, src)
}
func (m *RaftGetRequest) XXX_Size() int {
	return xxx_messageInfo_RaftGetRequest.Size(m)
}
func (m *RaftGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGetRequest proto.InternalMessageInfo

func (m *RaftGetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RaftGetResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftGetResponse) Reset()         { *m = RaftGetResponse{} }
func (m *RaftGetResponse) String() string { return proto.CompactTextString(m) }
func (*RaftGetResponse) ProtoMessage()    {}
func (*RaftGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{1}
}

func (m *RaftGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftGetResponse.Unmarshal(m, b)
}
func (m *RaftGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftGetResponse.Marshal(b, m, deterministic)
}
func (m *RaftGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGetResponse.Merge(m, src)
}
func (m *RaftGetResponse) XXX_Size() int {
	return xxx_messageInfo_RaftGetResponse.Size(m)
}
func (m *RaftGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGetResponse proto.InternalMessageInfo

func (m *RaftGetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RaftSetKeyValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftSetKeyValueRequest) Reset()         { *m = RaftSetKeyValueRequest{} }
func (m *RaftSetKeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*RaftSetKeyValueRequest) ProtoMessage()    {}
func (*RaftSetKeyValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{2}
}

func (m *RaftSetKeyValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftSetKeyValueRequest.Unmarshal(m, b)
}
func (m *RaftSetKeyValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftSetKeyValueRequest.Marshal(b, m, deterministic)
}
func (m *RaftSetKeyValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftSetKeyValueRequest.Merge(m, src)
}
func (m *RaftSetKeyValueRequest) XXX_Size() int {
	return xxx_messageInfo_RaftSetKeyValueRequest.Size(m)
}
func (m *RaftSetKeyValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftSetKeyValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftSetKeyValueRequest proto.InternalMessageInfo

func (m *RaftSetKeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RaftSetKeyValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RaftSetKeyValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftSetKeyValueResponse) Reset()         { *m = RaftSetKeyValueResponse{} }
func (m *RaftSetKeyValueResponse) String() string { return proto.CompactTextString(m) }
func (*RaftSetKeyValueResponse) ProtoMessage()    {}
func (*RaftSetKeyValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{3}
}

func (m *RaftSetKeyValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftSetKeyValueResponse.Unmarshal(m, b)
}
func (m *RaftSetKeyValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftSetKeyValueResponse.Marshal(b, m, deterministic)
}
func (m *RaftSetKeyValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftSetKeyValueResponse.Merge(m, src)
}
func (m *RaftSetKeyValueResponse) XXX_Size() int {
	return xxx_messageInfo_RaftSetKeyValueResponse.Size(m)
}
func (m *RaftSetKeyValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftSetKeyValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftSetKeyValueResponse proto.InternalMessageInfo

type RaftDeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftDeleteRequest) Reset()         { *m = RaftDeleteRequest{} }
func (m *RaftDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RaftDeleteRequest) ProtoMessage()    {}
func (*RaftDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{4}
}

func (m *RaftDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftDeleteRequest.Unmarshal(m, b)
}
func (m *RaftDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RaftDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftDeleteRequest.Merge(m, src)
}
func (m *RaftDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RaftDeleteRequest.Size(m)
}
func (m *RaftDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftDeleteRequest proto.InternalMessageInfo

func (m *RaftDeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RaftDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftDeleteResponse) Reset()         { *m = RaftDeleteResponse{} }
func (m *RaftDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RaftDeleteResponse) ProtoMessage()    {}
func (*RaftDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{5}
}

func (m *RaftDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftDeleteResponse.Unmarshal(m, b)
}
func (m *RaftDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RaftDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftDeleteResponse.Merge(m, src)
}
func (m *RaftDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RaftDeleteResponse.Size(m)
}
func (m *RaftDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftDeleteResponse proto.InternalMessageInfo

type RaftJoinRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	NodeAddress          string   `protobuf:"bytes,2,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftJoinRequest) Reset()         { *m = RaftJoinRequest{} }
func (m *RaftJoinRequest) String() string { return proto.CompactTextString(m) }
func (*RaftJoinRequest) ProtoMessage()    {}
func (*RaftJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{6}
}

func (m *RaftJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftJoinRequest.Unmarshal(m, b)
}
func (m *RaftJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftJoinRequest.Marshal(b, m, deterministic)
}
func (m *RaftJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftJoinRequest.Merge(m, src)
}
func (m *RaftJoinRequest) XXX_Size() int {
	return xxx_messageInfo_RaftJoinRequest.Size(m)
}
func (m *RaftJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftJoinRequest proto.InternalMessageInfo

func (m *RaftJoinRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *RaftJoinRequest) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

type RaftJoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftJoinResponse) Reset()         { *m = RaftJoinResponse{} }
func (m *RaftJoinResponse) String() string { return proto.CompactTextString(m) }
func (*RaftJoinResponse) ProtoMessage()    {}
func (*RaftJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{7}
}

func (m *RaftJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftJoinResponse.Unmarshal(m, b)
}
func (m *RaftJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftJoinResponse.Marshal(b, m, deterministic)
}
func (m *RaftJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftJoinResponse.Merge(m, src)
}
func (m *RaftJoinResponse) XXX_Size() int {
	return xxx_messageInfo_RaftJoinResponse.Size(m)
}
func (m *RaftJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftJoinResponse proto.InternalMessageInfo

type RaftGetAllUsrKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftGetAllUsrKeysRequest) Reset()         { *m = RaftGetAllUsrKeysRequest{} }
func (m *RaftGetAllUsrKeysRequest) String() string { return proto.CompactTextString(m) }
func (*RaftGetAllUsrKeysRequest) ProtoMessage()    {}
func (*RaftGetAllUsrKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{8}
}

func (m *RaftGetAllUsrKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftGetAllUsrKeysRequest.Unmarshal(m, b)
}
func (m *RaftGetAllUsrKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftGetAllUsrKeysRequest.Marshal(b, m, deterministic)
}
func (m *RaftGetAllUsrKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGetAllUsrKeysRequest.Merge(m, src)
}
func (m *RaftGetAllUsrKeysRequest) XXX_Size() int {
	return xxx_messageInfo_RaftGetAllUsrKeysRequest.Size(m)
}
func (m *RaftGetAllUsrKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGetAllUsrKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGetAllUsrKeysRequest proto.InternalMessageInfo

type RaftGetAllUsrKeysResponse struct {
	Value                []string `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftGetAllUsrKeysResponse) Reset()         { *m = RaftGetAllUsrKeysResponse{} }
func (m *RaftGetAllUsrKeysResponse) String() string { return proto.CompactTextString(m) }
func (*RaftGetAllUsrKeysResponse) ProtoMessage()    {}
func (*RaftGetAllUsrKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc897006fb7f154, []int{9}
}

func (m *RaftGetAllUsrKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftGetAllUsrKeysResponse.Unmarshal(m, b)
}
func (m *RaftGetAllUsrKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftGetAllUsrKeysResponse.Marshal(b, m, deterministic)
}
func (m *RaftGetAllUsrKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftGetAllUsrKeysResponse.Merge(m, src)
}
func (m *RaftGetAllUsrKeysResponse) XXX_Size() int {
	return xxx_messageInfo_RaftGetAllUsrKeysResponse.Size(m)
}
func (m *RaftGetAllUsrKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftGetAllUsrKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftGetAllUsrKeysResponse proto.InternalMessageInfo

func (m *RaftGetAllUsrKeysResponse) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*RaftGetRequest)(nil), "raftd.RaftGetRequest")
	proto.RegisterType((*RaftGetResponse)(nil), "raftd.RaftGetResponse")
	proto.RegisterType((*RaftSetKeyValueRequest)(nil), "raftd.RaftSetKeyValueRequest")
	proto.RegisterType((*RaftSetKeyValueResponse)(nil), "raftd.RaftSetKeyValueResponse")
	proto.RegisterType((*RaftDeleteRequest)(nil), "raftd.RaftDeleteRequest")
	proto.RegisterType((*RaftDeleteResponse)(nil), "raftd.RaftDeleteResponse")
	proto.RegisterType((*RaftJoinRequest)(nil), "raftd.RaftJoinRequest")
	proto.RegisterType((*RaftJoinResponse)(nil), "raftd.RaftJoinResponse")
	proto.RegisterType((*RaftGetAllUsrKeysRequest)(nil), "raftd.RaftGetAllUsrKeysRequest")
	proto.RegisterType((*RaftGetAllUsrKeysResponse)(nil), "raftd.RaftGetAllUsrKeysResponse")
}

func init() { proto.RegisterFile("raftservice.proto", fileDescriptor_ebc897006fb7f154) }

var fileDescriptor_ebc897006fb7f154 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x4b, 0x02, 0x41,
	0x10, 0x46, 0x45, 0xcd, 0x09, 0x4a, 0x07, 0xf3, 0xc7, 0x42, 0x25, 0x0b, 0x51, 0x4f, 0x42, 0xf5,
	0x12, 0xf4, 0x92, 0x21, 0x44, 0x1d, 0x44, 0x18, 0xf9, 0xd0, 0x9b, 0x76, 0x23, 0x08, 0x87, 0x67,
	0xb7, 0x6b, 0x70, 0x7f, 0x73, 0xff, 0x44, 0xec, 0xed, 0xe8, 0xed, 0x75, 0xde, 0xdb, 0xee, 0xcc,
	0xf7, 0x7d, 0xb3, 0xf3, 0x7d, 0x77, 0xd0, 0x8a, 0x66, 0x0b, 0xad, 0x28, 0xfa, 0x59, 0x7e, 0xd1,
	0x70, 0x1d, 0x85, 0x3a, 0xc4, 0xaa, 0x29, 0xf9, 0x52, 0xc2, 0xd1, 0x64, 0xb6, 0xd0, 0x4f, 0xa4,
	0x27, 0xf4, 0xbd, 0x21, 0xa5, 0xb1, 0x09, 0x15, 0x8f, 0xe2, 0x5e, 0x69, 0x50, 0xba, 0x6a, 0x4c,
	0xcc, 0x51, 0x5e, 0xc2, 0xf1, 0x0e, 0xa3, 0xd6, 0xe1, 0x4a, 0x11, 0xb6, 0xa1, 0x3a, 0x9d, 0x05,
	0x1b, 0x62, 0x98, 0xbd, 0xc8, 0x07, 0xe8, 0x18, 0xe0, 0x3b, 0x69, 0x8f, 0xe2, 0xa4, 0x54, 0x28,
	0x9a, 0x2a, 0x94, 0x5d, 0x85, 0x3e, 0x74, 0x73, 0x0a, 0x76, 0xa4, 0xbc, 0x80, 0x96, 0x69, 0x8d,
	0x29, 0x20, 0x5d, 0xac, 0x2b, 0xdb, 0x80, 0x2e, 0x8c, 0xc9, 0x9e, 0x5d, 0xe1, 0x25, 0x5c, 0xae,
	0xb6, 0xd4, 0x0e, 0xd4, 0x5e, 0x43, 0x9f, 0x9e, 0xc7, 0xcc, 0xe6, 0x1b, 0x0e, 0xe0, 0xd0, 0x9c,
	0x46, 0xbe, 0x1f, 0x91, 0x52, 0xfc, 0x3c, 0xb7, 0x24, 0x11, 0x9a, 0xa9, 0x18, 0x0f, 0x10, 0xd0,
	0x63, 0x8f, 0x46, 0x41, 0xf0, 0xa1, 0x22, 0x8f, 0x62, 0xc5, 0x93, 0xe4, 0x35, 0xf4, 0xf7, 0xf4,
	0xf2, 0x4e, 0x56, 0x76, 0x3e, 0xdc, 0xfc, 0x96, 0xa1, 0x6a, 0x38, 0x3e, 0xde, 0x41, 0x9d, 0xc9,
	0x78, 0x32, 0x4c, 0x32, 0x1b, 0x66, 0x03, 0x13, 0x9d, 0xff, 0x65, 0x56, 0x7e, 0xb3, 0x3b, 0x3b,
	0x5e, 0xe2, 0xa9, 0x03, 0xcd, 0xa7, 0x24, 0xce, 0x8a, 0xda, 0xac, 0x38, 0x02, 0x48, 0xbd, 0xc5,
	0x9e, 0x83, 0xce, 0xa4, 0x22, 0xfa, 0x7b, 0x3a, 0x2c, 0x71, 0x0f, 0x07, 0x5b, 0xef, 0xd0, 0x7d,
	0xb8, 0x93, 0x8c, 0xe8, 0xe6, 0xea, 0x4c, 0x9e, 0xda, 0x4f, 0x20, 0x63, 0x24, 0x9e, 0x67, 0xd7,
	0xcf, 0xd9, 0x2f, 0x06, 0xc5, 0x00, 0xab, 0xfb, 0xd8, 0xf8, 0xac, 0x27, 0x90, 0xf5, 0x7c, 0x5e,
	0x4b, 0xfe, 0x8e, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x83, 0xb6, 0xe0, 0x32, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftdClient is the client API for Raftd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftdClient interface {
	RaftGet(ctx context.Context, in *RaftGetRequest, opts ...grpc.CallOption) (*RaftGetResponse, error)
	RaftSetKeyValue(ctx context.Context, in *RaftSetKeyValueRequest, opts ...grpc.CallOption) (*RaftSetKeyValueResponse, error)
	RaftDelete(ctx context.Context, in *RaftDeleteRequest, opts ...grpc.CallOption) (*RaftDeleteResponse, error)
	RaftJoin(ctx context.Context, in *RaftJoinRequest, opts ...grpc.CallOption) (*RaftJoinResponse, error)
	RaftGetAllUsrKeys(ctx context.Context, in *RaftGetAllUsrKeysRequest, opts ...grpc.CallOption) (*RaftGetAllUsrKeysResponse, error)
}

type raftdClient struct {
	cc *grpc.ClientConn
}

func NewRaftdClient(cc *grpc.ClientConn) RaftdClient {
	return &raftdClient{cc}
}

func (c *raftdClient) RaftGet(ctx context.Context, in *RaftGetRequest, opts ...grpc.CallOption) (*RaftGetResponse, error) {
	out := new(RaftGetResponse)
	err := c.cc.Invoke(ctx, "/raftd.Raftd/RaftGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftdClient) RaftSetKeyValue(ctx context.Context, in *RaftSetKeyValueRequest, opts ...grpc.CallOption) (*RaftSetKeyValueResponse, error) {
	out := new(RaftSetKeyValueResponse)
	err := c.cc.Invoke(ctx, "/raftd.Raftd/RaftSetKeyValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftdClient) RaftDelete(ctx context.Context, in *RaftDeleteRequest, opts ...grpc.CallOption) (*RaftDeleteResponse, error) {
	out := new(RaftDeleteResponse)
	err := c.cc.Invoke(ctx, "/raftd.Raftd/RaftDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftdClient) RaftJoin(ctx context.Context, in *RaftJoinRequest, opts ...grpc.CallOption) (*RaftJoinResponse, error) {
	out := new(RaftJoinResponse)
	err := c.cc.Invoke(ctx, "/raftd.Raftd/RaftJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftdClient) RaftGetAllUsrKeys(ctx context.Context, in *RaftGetAllUsrKeysRequest, opts ...grpc.CallOption) (*RaftGetAllUsrKeysResponse, error) {
	out := new(RaftGetAllUsrKeysResponse)
	err := c.cc.Invoke(ctx, "/raftd.Raftd/RaftGetAllUsrKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftdServer is the server API for Raftd service.
type RaftdServer interface {
	RaftGet(context.Context, *RaftGetRequest) (*RaftGetResponse, error)
	RaftSetKeyValue(context.Context, *RaftSetKeyValueRequest) (*RaftSetKeyValueResponse, error)
	RaftDelete(context.Context, *RaftDeleteRequest) (*RaftDeleteResponse, error)
	RaftJoin(context.Context, *RaftJoinRequest) (*RaftJoinResponse, error)
	RaftGetAllUsrKeys(context.Context, *RaftGetAllUsrKeysRequest) (*RaftGetAllUsrKeysResponse, error)
}

func RegisterRaftdServer(s *grpc.Server, srv RaftdServer) {
	s.RegisterService(&_Raftd_serviceDesc, srv)
}

func _Raftd_RaftGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftdServer).RaftGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftd.Raftd/RaftGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftdServer).RaftGet(ctx, req.(*RaftGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raftd_RaftSetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftSetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftdServer).RaftSetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftd.Raftd/RaftSetKeyValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftdServer).RaftSetKeyValue(ctx, req.(*RaftSetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raftd_RaftDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftdServer).RaftDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftd.Raftd/RaftDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftdServer).RaftDelete(ctx, req.(*RaftDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raftd_RaftJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftdServer).RaftJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftd.Raftd/RaftJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftdServer).RaftJoin(ctx, req.(*RaftJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raftd_RaftGetAllUsrKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftGetAllUsrKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftdServer).RaftGetAllUsrKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftd.Raftd/RaftGetAllUsrKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftdServer).RaftGetAllUsrKeys(ctx, req.(*RaftGetAllUsrKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raftd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raftd.Raftd",
	HandlerType: (*RaftdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RaftGet",
			Handler:    _Raftd_RaftGet_Handler,
		},
		{
			MethodName: "RaftSetKeyValue",
			Handler:    _Raftd_RaftSetKeyValue_Handler,
		},
		{
			MethodName: "RaftDelete",
			Handler:    _Raftd_RaftDelete_Handler,
		},
		{
			MethodName: "RaftJoin",
			Handler:    _Raftd_RaftJoin_Handler,
		},
		{
			MethodName: "RaftGetAllUsrKeys",
			Handler:    _Raftd_RaftGetAllUsrKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raftservice.proto",
}
