// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contentd.proto

/*
Package contentdpb is a generated protocol buffer package.

It is generated from these files:
	contentd.proto
	service.proto

It has these top-level messages:
	Tweet
	NewTweet
	Comment
	NewComment
	NewTweetRequest
	NewTweetResponse
	GetTweetRequest
	GetTweetResponse
*/
package contentdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tweet struct {
	TID       string `protobuf:"bytes,1,opt,name=TID" json:"TID,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	PosterUID string `protobuf:"bytes,3,opt,name=PosterUID" json:"PosterUID,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
}

func (m *Tweet) Reset()                    { *m = Tweet{} }
func (m *Tweet) String() string            { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()               {}
func (*Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tweet) GetTID() string {
	if m != nil {
		return m.TID
	}
	return ""
}

func (m *Tweet) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Tweet) GetPosterUID() string {
	if m != nil {
		return m.PosterUID
	}
	return ""
}

func (m *Tweet) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewTweet struct {
	PosterUID string `protobuf:"bytes,1,opt,name=PosterUID" json:"PosterUID,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
}

func (m *NewTweet) Reset()                    { *m = NewTweet{} }
func (m *NewTweet) String() string            { return proto.CompactTextString(m) }
func (*NewTweet) ProtoMessage()               {}
func (*NewTweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewTweet) GetPosterUID() string {
	if m != nil {
		return m.PosterUID
	}
	return ""
}

func (m *NewTweet) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NewTweet) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Comment struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	ParentTID string `protobuf:"bytes,2,opt,name=ParentTID" json:"ParentTID,omitempty"`
	PosterUID string `protobuf:"bytes,3,opt,name=PosterUID" json:"PosterUID,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Comment) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Comment) GetParentTID() string {
	if m != nil {
		return m.ParentTID
	}
	return ""
}

func (m *Comment) GetPosterUID() string {
	if m != nil {
		return m.PosterUID
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewComment struct {
	ParentTID string `protobuf:"bytes,1,opt,name=ParentTID" json:"ParentTID,omitempty"`
	PosterUID string `protobuf:"bytes,2,opt,name=PosterUID" json:"PosterUID,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
}

func (m *NewComment) Reset()                    { *m = NewComment{} }
func (m *NewComment) String() string            { return proto.CompactTextString(m) }
func (*NewComment) ProtoMessage()               {}
func (*NewComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NewComment) GetParentTID() string {
	if m != nil {
		return m.ParentTID
	}
	return ""
}

func (m *NewComment) GetPosterUID() string {
	if m != nil {
		return m.PosterUID
	}
	return ""
}

func (m *NewComment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Tweet)(nil), "contentd.Tweet")
	proto.RegisterType((*NewTweet)(nil), "contentd.NewTweet")
	proto.RegisterType((*Comment)(nil), "contentd.Comment")
	proto.RegisterType((*NewComment)(nil), "contentd.NewComment")
}

func init() { proto.RegisterFile("contentd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x2b,
	0x49, 0xcd, 0x2b, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xf2,
	0xb9, 0x58, 0x43, 0xca, 0x53, 0x53, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x43, 0x3c, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x19, 0x2e, 0xce, 0x90, 0xcc, 0xdc, 0xd4, 0xe2,
	0x92, 0xc4, 0xdc, 0x02, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x84, 0x00, 0x48, 0x36, 0x20,
	0xbf, 0xb8, 0x24, 0xb5, 0x28, 0xd4, 0xd3, 0x45, 0x82, 0x19, 0xac, 0x0b, 0x21, 0x20, 0x24, 0xc1,
	0xc5, 0xee, 0x0c, 0xb1, 0x42, 0x82, 0x05, 0x2c, 0x07, 0xe3, 0x2a, 0x25, 0x70, 0x71, 0xf8, 0xa5,
	0x96, 0x43, 0xec, 0x44, 0x31, 0x83, 0x11, 0xdd, 0x0c, 0xfc, 0xf6, 0x23, 0xd9, 0xc0, 0x8c, 0x6a,
	0x43, 0x2d, 0x48, 0x26, 0x37, 0x37, 0x35, 0xaf, 0x04, 0xd5, 0x08, 0x46, 0x6c, 0x5e, 0x48, 0x2c,
	0x4a, 0xcd, 0x2b, 0x01, 0x79, 0x9c, 0x09, 0x6a, 0x3d, 0x4c, 0x80, 0x6c, 0x0f, 0x26, 0x71, 0x71,
	0xf9, 0xa5, 0x96, 0x23, 0xb9, 0x00, 0x61, 0x07, 0x23, 0x5e, 0x3b, 0x98, 0xf0, 0xd8, 0x81, 0xea,
	0x45, 0x27, 0x9e, 0x28, 0x2e, 0x58, 0x0c, 0x16, 0x24, 0x25, 0xb1, 0x81, 0x23, 0xd5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0x9e, 0x38, 0x0c, 0xe6, 0x01, 0x00, 0x00,
}
